---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
```
```{r}
heartrate<-read_csv("data/heartrate.csv")
heartrate
```
```{r}
glimpse(heartrate)
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate %>% 
  ggplot(aes(x=patient,fill=patient,y=a))+
  geom_col(alpha=0.6)+
  labs(title="Heartrates for Drug A",
       x=NULL,
       y="Drug A")+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5))
```

2. Make a plot that compares heartrate (as a range) for each drug.

```{r}
heartbeats_drug<-heartrate %>% 
  pivot_longer(a:d,
               names_to = "drug",
               values_to="heartbeats")
heartbeats_drug
```

```{r}
heartbeats_drug %>% 
  ggplot(aes(x=drug,fill=drug,y=heartbeats))+
  geom_boxplot(alpha=0.5)+
  labs(title="Heartbeats for Drugs",
       x="Drug",
       y="Heartbeats")+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5))
  
```

